spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional - Hibernate automatically detects MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# HikariCP settings
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000